[[headers]]
  # Set the correct Content-Type for JavaScript modules
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
